[Service]
ExecStart=
ExecStart=/bin/bash -c 'test -e /sys/bus/pci/devices/0000:08:00.0/remove && echo 1 > /sys/bus/pci/devices/0000:08:00.0/remove || echo "eGPU not present, skipping"'
RemainAfterExit=yes
