# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing

# Input method
# exec-once = fcitx5

exec-once = gnome-keyring-daemon --start --components=secrets

exec-once = hyprctl setcursor theme_oreo_noctalia_76946a_hyprcursor 28

exec-once = ~/.local/bin/noctalia-borders-watch.sh
exec-once = kdeconnectd
exec = hyprctl setcursor theme_oreo_noctalia_76946a_hyprcursor 28
